### ISSUE TITLE
[Missing Pieces] Compatibility request with Seasonality?

### ISSUE THREAD

**Issue by pjmichor** [OrianaVenture/Valheim-MissingPieces#16]
Hello!

My server is using [Seasonality ](https://thunderstore.io/c/valheim/p/RustyMods/Seasonality/) and would like to use these missing pieces too, but only 1 of the roof pieces (flat thatch) uses the current season's textures. Would it be possible to update the other roof pieces in the same manner?

Thanks!

**Comment by OrianaVenture** [comment]
Oh that's strange, they are all being mocked using the same vanilla textures so I would expect them all to work if one of them does. I'll reach out to Rusty and see if others have the same problem.

**Comment by pjmichor** [comment]
I only tested it for like 10min last night, so I might not have been too thorough.
I've seen plant/flora textures not update until the next in-game day, but didn't notice that with any of the building pieces. I'll check again today and report back. Just found it weird that one roof piece worked but not the others.

**Comment by pjmichor** [comment]
Hey @OrianaVenture, just wanted to ask if you've heard back from Rusty yet? Thanks!

**Comment by OrianaVenture** [comment]
I asked in their discord an nobody else is seeing the same issue with them. I have checked the unity project and don't see any differences in how the pieces are set up so I'm not sure what's going wrong. You could try reaching out to Rusty on his discord for more support, but there's not much I can do from my end since it's not a vanilla based issue and I don't have time to test Seasonality myself.

**Comment by pjmichor** [comment]
Hah, just me then? Gotta love when that happens. Thanks for asking around, mate!
