### ISSUE TITLE
[Suggestion] More Pieces (angles)

### ISSUE THREAD

**Issue by GrubbyZebra** [OrianaVenture/Valheim-MissingPieces#8]
Love the mod! Would it be possible to added some inverted roof triangle pieces and 45deg corner stairs (stone and wood) so it is easier to build chamfered corners?

**Comment by Xode007** [comment]
Agree with this, roof angles with 1 point at the top and 2 at the bottom would be very helpful. 

I would also like to see 1m roof pieces to help fill in small areas where the default 2m size have to overlap to fill. (or even 1m wide by 2m long if its necessary to keep the pattern repeating properly for the shingles)

If we do get the 1mx2m roofs i would love them to also have the angled flavours to help with less extreme roof overhangs than is necessary with the 45 degree ones. 

One piece i think is straight up missing is a piece that matches the roof topper that joins at the center of a tile, instead of on the edges, so the inside of the roof doesn't look janky when it sticks through 

Half size angle wood pieces. They are all currently a 2m size, but having some that fit the 1m template would help a lot with creativity IMO. (the angle pieces and the angle pieces combined with walls at least for the 45 degree one)

**Comment by OrianaVenture** [comment]
I like the wooden wall idea, but I will approach that use case a bit differently. Currently working on new quarter and half walls that line up with the top of the regular 2x2 wooden wall upper beam. Then combining the existing quarter wall and the new one will result in the "tall" half wall.

**Comment by OrianaVenture** [comment]
Closing this thread, will post an update in the new issue: https://github.com/OrianaVenture/Valheim-MissingPieces/issues/14
